export enum CompanyAuditOperation {
  CREATE = 'CREATE',
  UPDATE = 'UPDATE',
  DEACTIVATE = 'DEACTIVATE',
  REACTIVATE = 'REACTIVATE',
  ASSIGN_PROJECT_UNIT = 'ASSIGN_PROJECT_UNIT',
  REMOVE_PROJECT_UNIT = 'REMOVE_PROJECT_UNIT',
}
