export enum ExportJobAuditOperation {
  REQUEST = 'REQUEST',
  START = 'START',
  FINISH = 'FINISH',
  FAIL = 'FAIL',
  CANCEL = 'CANCEL',
  RETRY = 'RETRY',
  CREATE_DOWNLOAD_URL = 'CREATE_DOWNLOAD_URL',
  DOWNLOAD = 'DOWNLOAD',
  EXPIRE = 'EXPIRE',
  RECOVER_STALE = 'RECOVER_STALE',
}
