export enum AuthAuditOperation {
  LOGIN = 'LOGIN',
  LOGOUT = 'LOGOUT',
  LOGIN_FAILED = 'LOGIN_FAILED',
  PASSWORD_RESET_REQUEST = 'PASSWORD_RESET_REQUEST',
  PASSWORD_RESET_CONFIRM = 'PASSWORD_RESET_CONFIRM',
}

export enum AuthAuditResult {
  SUCCESS = 'SUCCESS',
  FAILURE = 'FAILURE',
}
