import { QueryClient, QueryClientProvider } from '@tanstack/react-query';
import { render, screen, waitFor } from '@testing-library/react';
import userEvent from '@testing-library/user-event';
import { MemoryRouter, Route, Routes } from 'react-router-dom';
import { beforeEach, describe, expect, it, vi } from 'vitest';
import { AuthContext, type AuthState } from '@/features/auth/AuthContext';
import type { CurrentUser, ExpenseAccountability } from '@/types/api';
import { ProjectAccountabilitiesPage } from './ProjectAccountabilitiesPage';
const mocks = vi.hoisted(() => ({ list: vi.fn(), create: vi.fn(), get: vi.fn(), addExpense: vi.fn(), close: vi.fn(), listInstallments: vi.fn(), generateInstallments: vi.fn(), expenses: vi.fn() }));
vi.mock('@/api/endpoints', () => ({ expenseAccountabilitiesApi: { list: mocks.list, create: mocks.create, get: mocks.get, addExpense: mocks.addExpense, close: mocks.close, listInstallments: mocks.listInstallments, generateInstallments: mocks.generateInstallments }, expensesApi: { list: mocks.expenses } }));
const accountability: ExpenseAccountability = { id: 8, organization_id: 1, project_id: 10, field_agent_id: 7, period_start: '2026-08-01', period_end: '2026-08-31', status: 'open', total_amount: '300.00', responsible_by_id: 1, expense_ids: [1, 2, 3], created_at: '2026-08-01T00:00:00Z', updated_at: '2026-08-01T00:00:00Z' };
const user: CurrentUser = { id: 1, login: 'admin', email: 'admin@gai.local', status: 'ACTIVE', organization_id: 1, permissions: ['expense-accountabilities:read', 'expense-accountabilities:create', 'expense-accountabilities:update', 'expense-accountabilities:close', 'expense-installments:read', 'expense-installments:create'].map((key) => ({ key, scope: 'ORGANIZATION' })), role_assignments: [] };
function renderPage() { const client = new QueryClient({ defaultOptions: { queries: { retry: false }, mutations: { retry: false } } }); const auth: AuthState = { user, accessToken: 'token', expiresAt: null, bootstrapping: false, login: vi.fn(), logout: vi.fn(), restore: vi.fn() }; return render(<QueryClientProvider client={client}><AuthContext.Provider value={auth}><MemoryRouter initialEntries={['/app/projects/10/finance/accountabilities']}><Routes><Route path="/app/projects/:projectId/finance/accountabilities" element={<ProjectAccountabilitiesPage />} /></Routes></MemoryRouter></AuthContext.Provider></QueryClientProvider>); }
describe('ProjectAccountabilitiesPage', () => { beforeEach(() => { vi.clearAllMocks(); mocks.list.mockResolvedValue({ items: [accountability], page: 1, page_size: 20, total_items: 1, total_pages: 1 }); mocks.get.mockResolvedValue(accountability); mocks.create.mockResolvedValue(accountability); mocks.expenses.mockResolvedValue({ items: [], page: 1, page_size: 100, total_items: 0, total_pages: 0 }); mocks.listInstallments.mockResolvedValue({ items: [], page: 1, page_size: 100, total_items: 0, total_pages: 0 }); }); it('exibe total e tres despesas retornados pelo backend', async () => { renderPage(); expect(await screen.findByText('R$ 300,00')).toBeInTheDocument(); expect(screen.getByText('3')).toBeInTheDocument(); }); it('envia filtros reais para a API', async () => { renderPage(); await userEvent.selectOptions(await screen.findByLabelText('Status da prestacao'), 'open'); await waitFor(() => expect(mocks.list).toHaveBeenLastCalledWith(10, expect.objectContaining({ status: 'open' }))); }); });
