import { DataSource } from 'typeorm';
import { PermissionScope } from '../../modules/users/domain/enums/permission-scope.enum';
import { PermissionEntity } from '../../modules/users/infrastructure/persistence/permission.entity';

export const PERMISSION_SEEDS: Array<{
  key: string;
  resource: string;
  action: string;
  scope: PermissionScope;
  description: string;
}> = [
  {
    key: 'organizations:read',
    resource: 'organizations',
    action: 'read',
    scope: PermissionScope.PLATFORM,
    description: 'Listar e consultar organizations',
  },
  {
    key: 'organizations:write',
    resource: 'organizations',
    action: 'write',
    scope: PermissionScope.PLATFORM,
    description: 'Criar e atualizar organizations',
  },
  {
    key: 'users:read',
    resource: 'users',
    action: 'read',
    scope: PermissionScope.ORGANIZATION,
    description: 'Listar e consultar usuários da organization',
  },
  {
    key: 'users:write',
    resource: 'users',
    action: 'write',
    scope: PermissionScope.ORGANIZATION,
    description: 'Criar e atualizar usuários da organization',
  },
  {
    key: 'org_roles:read',
    resource: 'org_roles',
    action: 'read',
    scope: PermissionScope.ORGANIZATION,
    description: 'Listar papéis customizados da organization',
  },
  {
    key: 'org_roles:write',
    resource: 'org_roles',
    action: 'write',
    scope: PermissionScope.ORGANIZATION,
    description: 'Gerenciar papéis customizados da organization',
  },
  {
    key: 'assets:read',
    resource: 'assets',
    action: 'read',
    scope: PermissionScope.ORGANIZATION,
    description: 'Reservado — leitura de ativos (módulo futuro)',
  },
  {
    key: 'assets:write',
    resource: 'assets',
    action: 'write',
    scope: PermissionScope.ORGANIZATION,
    description: 'Reservado — escrita de ativos (módulo futuro)',
  },
  {
    key: 'projects:create',
    resource: 'projects',
    action: 'create',
    scope: PermissionScope.ORGANIZATION,
    description: 'Criar projects da organization',
  },
  {
    key: 'projects:read',
    resource: 'projects',
    action: 'read',
    scope: PermissionScope.ORGANIZATION,
    description: 'Listar e consultar projects da organization',
  },
  {
    key: 'projects:update',
    resource: 'projects',
    action: 'update',
    scope: PermissionScope.ORGANIZATION,
    description: 'Atualizar projects da organization',
  },
  {
    key: 'projects:activate',
    resource: 'projects',
    action: 'activate',
    scope: PermissionScope.ORGANIZATION,
    description: 'Ativar projects da organization',
  },
  {
    key: 'projects:pause',
    resource: 'projects',
    action: 'pause',
    scope: PermissionScope.ORGANIZATION,
    description: 'Pausar projects da organization',
  },
  {
    key: 'projects:resume',
    resource: 'projects',
    action: 'resume',
    scope: PermissionScope.ORGANIZATION,
    description: 'Retomar projects da organization',
  },
  {
    key: 'projects:deactivate',
    resource: 'projects',
    action: 'deactivate',
    scope: PermissionScope.ORGANIZATION,
    description: 'Desativar projects da organization',
  },
  {
    key: 'projects:reactivate',
    resource: 'projects',
    action: 'reactivate',
    scope: PermissionScope.ORGANIZATION,
    description: 'Reativar projects da organization',
  },
  {
    key: 'projects:finish',
    resource: 'projects',
    action: 'finish',
    scope: PermissionScope.ORGANIZATION,
    description: 'Finalizar projects da organization',
  },
  {
    key: 'projects:cancel',
    resource: 'projects',
    action: 'cancel',
    scope: PermissionScope.ORGANIZATION,
    description: 'Cancelar projects da organization',
  },
  {
    key: 'projects:archive',
    resource: 'projects',
    action: 'archive',
    scope: PermissionScope.ORGANIZATION,
    description: 'Arquivar projects da organization',
  },
  {
    key: 'field-agents:create',
    resource: 'field-agents',
    action: 'create',
    scope: PermissionScope.ORGANIZATION,
    description: 'Criar inventariantes da organization',
  },
  {
    key: 'field-agents:read',
    resource: 'field-agents',
    action: 'read',
    scope: PermissionScope.ORGANIZATION,
    description: 'Listar e consultar inventariantes da organization',
  },
  {
    key: 'field-agents:update',
    resource: 'field-agents',
    action: 'update',
    scope: PermissionScope.ORGANIZATION,
    description: 'Atualizar inventariantes da organization',
  },
  {
    key: 'field-agents:deactivate',
    resource: 'field-agents',
    action: 'deactivate',
    scope: PermissionScope.ORGANIZATION,
    description: 'Desativar inventariantes da organization',
  },
  {
    key: 'field-agents:reactivate',
    resource: 'field-agents',
    action: 'reactivate',
    scope: PermissionScope.ORGANIZATION,
    description: 'Reativar inventariantes da organization',
  },
  {
    key: 'field-agents:block',
    resource: 'field-agents',
    action: 'block',
    scope: PermissionScope.ORGANIZATION,
    description: 'Bloquear inventariantes da organization',
  },
  {
    key: 'field-agents:unblock',
    resource: 'field-agents',
    action: 'unblock',
    scope: PermissionScope.ORGANIZATION,
    description: 'Desbloquear inventariantes da organization',
  },
  {
    key: 'field-agents:delete',
    resource: 'field-agents',
    action: 'delete',
    scope: PermissionScope.ORGANIZATION,
    description: 'Excluir inventariantes logicamente',
  },
  {
    key: 'project-field-agents:assign',
    resource: 'project-field-agents',
    action: 'assign',
    scope: PermissionScope.ORGANIZATION,
    description: 'Vincular inventariantes a projects',
  },
  {
    key: 'project-field-agents:read',
    resource: 'project-field-agents',
    action: 'read',
    scope: PermissionScope.ORGANIZATION,
    description: 'Listar inventariantes de projects',
  },
  {
    key: 'project-field-agents:update',
    resource: 'project-field-agents',
    action: 'update',
    scope: PermissionScope.ORGANIZATION,
    description: 'Atualizar vinculos de inventariantes em projects',
  },
  {
    key: 'project-field-agents:remove',
    resource: 'project-field-agents',
    action: 'remove',
    scope: PermissionScope.ORGANIZATION,
    description: 'Remover logicamente inventariantes de projects',
  },
  {
    key: 'inventory-items:create',
    resource: 'inventory-items',
    action: 'create',
    scope: PermissionScope.ORGANIZATION,
    description: 'Criar itens inventariados da organization',
  },
  {
    key: 'inventory-items:read',
    resource: 'inventory-items',
    action: 'read',
    scope: PermissionScope.ORGANIZATION,
    description: 'Listar e consultar itens inventariados da organization',
  },
  {
    key: 'inventory-items:update',
    resource: 'inventory-items',
    action: 'update',
    scope: PermissionScope.ORGANIZATION,
    description: 'Atualizar itens inventariados da organization',
  },
  {
    key: 'inventory-items:deactivate',
    resource: 'inventory-items',
    action: 'deactivate',
    scope: PermissionScope.ORGANIZATION,
    description: 'Desativar itens inventariados da organization',
  },
  {
    key: 'inventory-items:reactivate',
    resource: 'inventory-items',
    action: 'reactivate',
    scope: PermissionScope.ORGANIZATION,
    description: 'Reativar itens inventariados da organization',
  },
  {
    key: 'inventory-item-images:create',
    resource: 'inventory-item-images',
    action: 'create',
    scope: PermissionScope.ORGANIZATION,
    description: 'Criar URLs de upload de imagens dos itens inventariados',
  },
  {
    key: 'inventory-item-images:read',
    resource: 'inventory-item-images',
    action: 'read',
    scope: PermissionScope.ORGANIZATION,
    description: 'Listar e consultar imagens dos itens inventariados',
  },
  {
    key: 'inventory-item-images:update',
    resource: 'inventory-item-images',
    action: 'update',
    scope: PermissionScope.ORGANIZATION,
    description: 'Confirmar upload de imagens dos itens inventariados',
  },
  {
    key: 'inventory-item-images:remove',
    resource: 'inventory-item-images',
    action: 'remove',
    scope: PermissionScope.ORGANIZATION,
    description: 'Remover logicamente imagens dos itens inventariados',
  },
  {
    key: 'inventory-item-images:download',
    resource: 'inventory-item-images',
    action: 'download',
    scope: PermissionScope.ORGANIZATION,
    description: 'Gerar URLs de download de imagens dos itens inventariados',
  },
  {
    key: 'inventory-accounting-items:create',
    resource: 'inventory-accounting-items',
    action: 'create',
    scope: PermissionScope.ORGANIZATION,
    description: 'Criar itens da base contabil da organization',
  },
  {
    key: 'inventory-accounting-items:read',
    resource: 'inventory-accounting-items',
    action: 'read',
    scope: PermissionScope.ORGANIZATION,
    description: 'Listar e consultar itens da base contabil da organization',
  },
  {
    key: 'inventory-accounting-items:update',
    resource: 'inventory-accounting-items',
    action: 'update',
    scope: PermissionScope.ORGANIZATION,
    description: 'Atualizar itens da base contabil da organization',
  },
  {
    key: 'inventory-accounting-items:deactivate',
    resource: 'inventory-accounting-items',
    action: 'deactivate',
    scope: PermissionScope.ORGANIZATION,
    description: 'Desativar itens da base contabil da organization',
  },
  {
    key: 'inventory-accounting-items:reactivate',
    resource: 'inventory-accounting-items',
    action: 'reactivate',
    scope: PermissionScope.ORGANIZATION,
    description: 'Reativar itens da base contabil da organization',
  },
  {
    key: 'inventory-accounting-items:import',
    resource: 'inventory-accounting-items',
    action: 'import',
    scope: PermissionScope.ORGANIZATION,
    description: 'Importar planilhas da base contabil da organization',
  },
  {
    key: 'inventory-accounting-items:export-errors',
    resource: 'inventory-accounting-items',
    action: 'export-errors',
    scope: PermissionScope.ORGANIZATION,
    description: 'Consultar relatorios de erro da importacao contabil',
  },
  {
    key: 'inventory-pending-issues:create',
    resource: 'inventory-pending-issues',
    action: 'create',
    scope: PermissionScope.ORGANIZATION,
    description: 'Criar pendencias patrimoniais da organization',
  },
  {
    key: 'inventory-pending-issues:read',
    resource: 'inventory-pending-issues',
    action: 'read',
    scope: PermissionScope.ORGANIZATION,
    description: 'Listar e consultar pendencias patrimoniais da organization',
  },
  {
    key: 'inventory-pending-issues:update',
    resource: 'inventory-pending-issues',
    action: 'update',
    scope: PermissionScope.ORGANIZATION,
    description: 'Atualizar pendencias patrimoniais da organization',
  },
  {
    key: 'inventory-pending-issues:resolve',
    resource: 'inventory-pending-issues',
    action: 'resolve',
    scope: PermissionScope.ORGANIZATION,
    description: 'Resolver pendencias patrimoniais da organization',
  },
  {
    key: 'inventory-pending-issues:ignore',
    resource: 'inventory-pending-issues',
    action: 'ignore',
    scope: PermissionScope.ORGANIZATION,
    description: 'Ignorar pendencias patrimoniais da organization',
  },
  {
    key: 'inventory-pending-issues:cancel',
    resource: 'inventory-pending-issues',
    action: 'cancel',
    scope: PermissionScope.ORGANIZATION,
    description: 'Cancelar pendencias patrimoniais da organization',
  },
  {
    key: 'inventory-pending-issues:generate',
    resource: 'inventory-pending-issues',
    action: 'generate',
    scope: PermissionScope.ORGANIZATION,
    description: 'Gerar pendencias patrimoniais automaticamente',
  },
  ...[
    [
      'payments:create',
      'payments',
      'create',
      'Criar pagamentos de inventariantes',
    ],
    ['payments:read', 'payments', 'read', 'Listar e consultar pagamentos'],
    ['payments:update', 'payments', 'update', 'Atualizar pagamentos'],
    ['payments:approve', 'payments', 'approve', 'Aprovar pagamentos'],
    [
      'payments:mark-as-paid',
      'payments',
      'mark-as-paid',
      'Marcar pagamentos como pagos',
    ],
    ['payments:cancel', 'payments', 'cancel', 'Cancelar pagamentos'],
    ['payments:export', 'payments', 'export', 'Exportar pagamentos'],
    ['expenses:create', 'expenses', 'create', 'Criar despesas'],
    ['expenses:read', 'expenses', 'read', 'Listar e consultar despesas'],
    ['expenses:update', 'expenses', 'update', 'Atualizar despesas'],
    ['expenses:approve', 'expenses', 'approve', 'Aprovar despesas'],
    ['expenses:reject', 'expenses', 'reject', 'Rejeitar despesas'],
    [
      'expenses:mark-as-paid',
      'expenses',
      'mark-as-paid',
      'Marcar despesas como pagas',
    ],
    ['expenses:cancel', 'expenses', 'cancel', 'Cancelar despesas'],
    [
      'expenses:upload-attachment',
      'expenses',
      'upload-attachment',
      'Criar e confirmar comprovantes de despesas',
    ],
    [
      'expenses:download-attachment',
      'expenses',
      'download-attachment',
      'Baixar comprovantes de despesas',
    ],
  ].map(([key, resource, action, description]) => ({
    key,
    resource,
    action,
    scope: PermissionScope.ORGANIZATION,
    description,
  })),
  ...[
    [
      'import-sessions:create',
      'import-sessions',
      'create',
      'Criar sessoes de importacao',
    ],
    [
      'import-sessions:read',
      'import-sessions',
      'read',
      'Listar e consultar sessoes de importacao',
    ],
    [
      'import-sessions:finish',
      'import-sessions',
      'finish',
      'Finalizar sessoes de importacao',
    ],
    [
      'import-sessions:cancel',
      'import-sessions',
      'cancel',
      'Cancelar sessoes de importacao',
    ],
    [
      'import-sessions:retry',
      'import-sessions',
      'retry',
      'Reprocessar sessoes com falha',
    ],
    [
      'import-payloads:create',
      'import-payloads',
      'create',
      'Receber payloads de importacao',
    ],
    [
      'import-payloads:read',
      'import-payloads',
      'read',
      'Listar e consultar payloads de importacao',
    ],
    [
      'import-payloads:reprocess',
      'import-payloads',
      'reprocess',
      'Reprocessar payloads com falha',
    ],
    [
      'import-errors:read',
      'import-errors',
      'read',
      'Consultar erros de importacao',
    ],
    [
      'import-files:create',
      'import-files',
      'create',
      'Criar e confirmar arquivos de importacao',
    ],
    [
      'import-files:read',
      'import-files',
      'read',
      'Listar arquivos de importacao',
    ],
    [
      'import-files:download',
      'import-files',
      'download',
      'Baixar arquivos de importacao',
    ],
  ].map(([key, resource, action, description]) => ({
    key,
    resource,
    action,
    scope: PermissionScope.ORGANIZATION,
    description,
  })),
  {
    key: 'catalog-assets:create',
    resource: 'catalog-assets',
    action: 'create',
    scope: PermissionScope.ORGANIZATION,
    description: 'Criar ativos do catalogo da organization',
  },
  {
    key: 'catalog-assets:read',
    resource: 'catalog-assets',
    action: 'read',
    scope: PermissionScope.ORGANIZATION,
    description: 'Listar e consultar ativos do catalogo da organization',
  },
  {
    key: 'catalog-assets:update',
    resource: 'catalog-assets',
    action: 'update',
    scope: PermissionScope.ORGANIZATION,
    description: 'Atualizar ativos do catalogo da organization',
  },
  {
    key: 'catalog-assets:deactivate',
    resource: 'catalog-assets',
    action: 'deactivate',
    scope: PermissionScope.ORGANIZATION,
    description: 'Desativar ativos do catalogo da organization',
  },
  {
    key: 'catalog-assets:reactivate',
    resource: 'catalog-assets',
    action: 'reactivate',
    scope: PermissionScope.ORGANIZATION,
    description: 'Reativar ativos do catalogo da organization',
  },
  ...[
    ['export-jobs:create', 'create', 'Solicitar exportacoes de projects'],
    ['export-jobs:read', 'read', 'Listar e consultar exportacoes de projects'],
    ['export-jobs:download', 'download', 'Baixar exportacoes de projects'],
    ['export-jobs:cancel', 'cancel', 'Cancelar exportacoes de projects'],
    ['export-jobs:retry', 'retry', 'Repetir exportacoes de projects'],
  ].map(([key, action, description]) => ({
    key,
    resource: 'export-jobs',
    action,
    scope: PermissionScope.ORGANIZATION,
    description,
  })),
  ...[
    [
      'companies:create',
      'companies',
      'create',
      'Criar companies da organization',
    ],
    ['companies:read', 'companies', 'read', 'Listar e consultar companies'],
    ['companies:update', 'companies', 'update', 'Atualizar companies'],
    ['companies:deactivate', 'companies', 'deactivate', 'Desativar companies'],
    ['companies:reactivate', 'companies', 'reactivate', 'Reativar companies'],
    [
      'company-units:create',
      'company-units',
      'create',
      'Criar unidades de companies',
    ],
    [
      'company-units:read',
      'company-units',
      'read',
      'Listar e consultar unidades de companies',
    ],
    [
      'company-units:update',
      'company-units',
      'update',
      'Atualizar unidades de companies',
    ],
    [
      'company-units:deactivate',
      'company-units',
      'deactivate',
      'Desativar unidades de companies',
    ],
    [
      'company-units:reactivate',
      'company-units',
      'reactivate',
      'Reativar unidades de companies',
    ],
    [
      'project-units:assign',
      'project-units',
      'assign',
      'Vincular unidades a projects',
    ],
    [
      'project-units:read',
      'project-units',
      'read',
      'Listar unidades de projects',
    ],
    [
      'project-units:remove',
      'project-units',
      'remove',
      'Remover unidades de projects',
    ],
  ].map(([key, resource, action, description]) => ({
    key,
    resource,
    action,
    scope: PermissionScope.ORGANIZATION,
    description,
  })),
];

export async function seedPermissions(dataSource: DataSource): Promise<void> {
  const repo = dataSource.getRepository(PermissionEntity);

  for (const seed of PERMISSION_SEEDS) {
    const existing = await repo.findOne({ where: { key: seed.key } });
    if (!existing) {
      await repo.save(repo.create(seed));
    }
  }
}
