import { cn } from '@/utils/cn';

const tone: Record<string, string> = {
  ACTIVE: 'bg-success-subtle text-success ring-success/20',
  active: 'bg-success-subtle text-success ring-success/20',
  evaluated: 'bg-success-subtle text-success ring-success/20',
  uploaded: 'bg-success-subtle text-success ring-success/20',
  paid: 'bg-success-subtle text-success ring-success/20',
  matched: 'bg-success-subtle text-success ring-success/20',
  resolved: 'bg-success-subtle text-success ring-success/20',
  processed: 'bg-success-subtle text-success ring-success/20',
  INACTIVE: 'bg-muted text-muted-foreground ring-border',
  inactive: 'bg-muted text-muted-foreground ring-border',
  archived: 'bg-muted text-muted-foreground ring-border',
  removed: 'bg-muted text-muted-foreground ring-border',
  ignored: 'bg-muted text-muted-foreground ring-border',
  expired: 'bg-muted text-muted-foreground ring-border',
  low: 'bg-muted text-muted-foreground ring-border',
  LOCKED: 'bg-destructive/10 text-destructive ring-destructive/20',
  blocked: 'bg-destructive/10 text-destructive ring-destructive/20',
  failed: 'bg-destructive/10 text-destructive ring-destructive/20',
  rejected: 'bg-destructive/10 text-destructive ring-destructive/20',
  cancelled: 'bg-destructive/10 text-destructive ring-destructive/20',
  not_found: 'bg-destructive/10 text-destructive ring-destructive/20',
  critical: 'bg-destructive/10 text-destructive ring-destructive/20',
  divergent: 'bg-destructive/10 text-destructive ring-destructive/20',
  high: 'bg-destructive/10 text-destructive ring-destructive/20',
  pending_upload: 'bg-warning-subtle text-warning-foreground ring-warning/25 dark:text-warning',
  pending: 'bg-warning-subtle text-warning-foreground ring-warning/25 dark:text-warning',
  paused: 'bg-warning-subtle text-warning-foreground ring-warning/25 dark:text-warning',
  duplicated: 'bg-warning-subtle text-warning-foreground ring-warning/25 dark:text-warning',
  open: 'bg-warning-subtle text-warning-foreground ring-warning/25 dark:text-warning',
  medium: 'bg-warning-subtle text-warning-foreground ring-warning/25 dark:text-warning',
  draft: 'bg-info-subtle text-info ring-info/20',
  approved: 'bg-info-subtle text-info ring-info/20',
  processing: 'bg-info-subtle text-info ring-info/20',
  receiving: 'bg-info-subtle text-info ring-info/20',
  received: 'bg-info-subtle text-info ring-info/20',
  in_review: 'bg-info-subtle text-info ring-info/20',
  finished: 'bg-accent text-accent-foreground ring-chart-2/20',
};

const label: Record<string, string> = {
  ACTIVE: 'Ativo',
  active: 'Ativo',
  INACTIVE: 'Inativo',
  inactive: 'Inativo',
  LOCKED: 'Bloqueado',
  blocked: 'Bloqueado',
  draft: 'Rascunho',
  paused: 'Pausado',
  finished: 'Finalizado',
  cancelled: 'Cancelado',
  archived: 'Arquivado',
  pending_upload: 'Aguardando upload',
  uploaded: 'Enviado',
  failed: 'Falhou',
  removed: 'Removido',
  expired: 'Expirado',
  pending: 'Pendente',
  approved: 'Aprovado',
  paid: 'Pago',
  rejected: 'Rejeitado',
  matched: 'Conciliado',
  divergent: 'Divergente',
  not_found: 'Nao encontrado',
  ignored: 'Ignorado',
  processing: 'Processando',
  receiving: 'Recebendo',
  received: 'Recebido',
  processed: 'Processado',
  duplicated: 'Duplicado',
  open: 'Aberto',
  in_review: 'Em revisao',
  resolved: 'Resolvido',
  evaluated: 'Avaliado',
  low: 'Baixa',
  medium: 'Media',
  high: 'Alta',
  critical: 'Critica',
};

export function StatusBadge({ value }: { value?: string | null }) {
  const raw = value ?? '-';
  return <span title={raw} className={cn('inline-flex items-center gap-1.5 rounded-full px-2.5 py-1 text-[0.6875rem] font-bold tracking-wide ring-1 ring-inset before:size-1.5 before:rounded-full before:bg-current before:opacity-75', tone[raw] ?? 'bg-muted text-muted-foreground ring-border')}>{label[raw] ?? raw}</span>;
}
