export enum FieldAgentAuditOperation {
  CREATE = 'CREATE',
  UPDATE = 'UPDATE',
  DEACTIVATE = 'DEACTIVATE',
  REACTIVATE = 'REACTIVATE',
  BLOCK = 'BLOCK',
  UNBLOCK = 'UNBLOCK',
  DELETE = 'DELETE',
  ASSIGN_TO_PROJECT = 'ASSIGN_TO_PROJECT',
  UPDATE_PROJECT_ASSIGNMENT = 'UPDATE_PROJECT_ASSIGNMENT',
  REMOVE_FROM_PROJECT = 'REMOVE_FROM_PROJECT',
}
